config/routes.rb
Rails.application.routes.draw do
  resources :contacts
  root 'contacts#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :contact
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
	has_one_attached :avatar
	def full_name
		if self.first_name.present? && self.last_name.present?
			"#{self.first_name} #{self.last_name}"
		end
	end

	def my_avatar
		if self.avatar.attached?
			self.avatar.variant(resize_to_fill: [150, 150], quality: 100, gravity: "center")
		else
			"https://via.placeholder.com/150"
		end

	end
	has_many :phones, dependent: :destroy
	accepts_nested_attributes_for :phones, reject_if: :all_blank, allow_destroy: true

	has_many :emails, dependent: :destroy
	accepts_nested_attributes_for :emails, reject_if: :all_blank, allow_destroy: true

	has_many :addresses, dependent: :destroy
	accepts_nested_attributes_for :addresses, reject_if: :all_blank, allow_destroy: true


end

app/models/email.rb
class Email < ApplicationRecord
  belongs_to :contact
end

app/models/phone.rb
class Phone < ApplicationRecord
  belongs_to :contact
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: [:show, :edit, :update, :destroy]

  # GET /contacts
  # GET /contacts.json
  def index
    @contacts = Contact.all
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
        format.html { redirect_to @contact, notice: 'Contact was successfully created.' }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to @contact, notice: 'Contact was successfully updated.' }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url, notice: 'Contact was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def contact_params
      params.require(:contact).permit(
        :first_name, 
        :last_name, 
        :company,
        :avatar,
        phones_attributes: [
          :id, 
          :label,
          :phone_number,
          :_destroy
        ],
        emails_attributes: [
          :id, 
          :label,
          :my_email,
          :_destroy
        ],
        addresses_attributes: [
          :id, 
          :label,
          :my_address,
          :_destroy
        ]
        )
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
	ALERT_TYPES = [:success, :info, :warning, :danger] unless const_defined?(:ALERT_TYPES)

	def bootstrap_flash(options = {})
	    flash_messages = []
	    flash.each do |type, message|
	      # Skip empty messages, e.g. for devise messages set to nothing in a locale file.
	      next if message.blank?

	      type = type.to_sym
	      type = :success if type == :notice
	      type = :danger  if type == :alert
	      type = :danger  if type == :error
	      next unless ALERT_TYPES.include?(type)

	      tag_class = options.extract!(:class)[:class]
	      tag_options = {
	        class: "alert alert-#{type} #{tag_class}",
	        	id: "success-alert"
	      }.merge(options)

	      close_button = content_tag(:button, raw("&times;"), type: "button", class: "close", "data-dismiss" => "alert")

	      Array(message).each do |msg|
	        text = content_tag(:div, close_button + msg, tag_options)
	        flash_messages << text if msg
	      end
	    end
	    flash_messages.join("\n").html_safe
	end

end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contacts/_address_fields.html.erb
<div class="nested-fields">
  <div class="input-group">
    <%= f.text_field :label, class: "form-control", placeholder: :label   %>
    <%= f.text_field :my_address, class: "form-control", placeholder: :my_address   %>
    
    <div class="input-group-append">
      <%= link_to_remove_association f, class: "mb-2 btn btn-outline-danger" do %>
        Remove
      <% end %>
    </div>
  </div>
</div>

app/views/contacts/_email_fields.html.erb
<div class="nested-fields">
  <div class="input-group">
    <%= f.text_field :label, class: "form-control", placeholder: :label   %>
    <%= f.text_field :my_email, class: "form-control", placeholder: :my_email   %>
    
    <div class="input-group-append">
      <%= link_to_remove_association f, class: "mb-2 btn btn-outline-danger" do %>
        Remove
      <% end %>
    </div>
  </div>
</div>

app/views/contacts/_form.html.erb
<%= form_with(model: contact, local: true) do |form| %>
  <% if contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
        <% contact.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= form.label :avatar %>
    <%= form.file_field :avatar %>
  </div>

  <div class="form-group">
    <%= form.label :first_name %>
    <%= form.text_field :first_name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :last_name %>
    <%= form.text_field :last_name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :company %>
    <%= form.text_field :company, class: "form-control" %>
  </div>


<div class="form-group">
  <%= form.label :phone %>
  <%= form.fields_for :phones do |phone| %>
    <%= render 'phone_fields', f: phone %>
  <% end %>
  <div class='my-4'>
    <%= link_to_add_association 'Add Phone', form, :phones, class: "btn btn-success btn-sm" %>
  </div>
</div>

<div class="form-group">
  <%= form.label :email %>
  <%= form.fields_for :emails do |email| %>
    <%= render 'email_fields', f: email %>
  <% end %>
  <div class='my-4'>
    <%= link_to_add_association 'Add email', form, :emails, class: "btn btn-success btn-sm" %>
  </div>
</div>

<div class="form-group">
  <%= form.label :address %>
  <%= form.fields_for :addresses do |address| %>
    <%= render 'address_fields', f: address %>
  <% end %>
  <div class='my-4'>
    <%= link_to_add_association 'Add address', form, :addresses, class: "btn btn-success btn-sm" %>
  </div>
</div>
  

  <div class="form-group">
    <%= form.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/contacts/_phone_fields.html.erb
<div class="nested-fields">
  <div class="input-group">
    <%= f.text_field :label, class: "form-control", placeholder: :label   %>
    <%= f.text_field :phone_number, class: "form-control", placeholder: :phone_number   %>
    
    <div class="input-group-append">
      <%= link_to_remove_association f, class: "mb-2 btn btn-outline-danger" do %>
        Remove
      <% end %>
    </div>
  </div>
</div>

app/views/contacts/edit.html.erb
<div class="row">
	<div class="col-md-6 offset-md-3">
		<div class="card">
			<div class="card-header">
				<h1 class="card-title h3">Editing Contact</h1>
			</div>
			<div class="card-body">
				<%= render 'form', contact: @contact %>
				<%= link_to 'Back', contacts_path %>
			</div>
		</div>
	</div>
</div>

app/views/contacts/index.html.erb
<h1>Contacts List</h1>

<div class="list-group">
  <% @contacts.each do |contact| %>
  <div class="list-group-item list-group-item-action flex-column align-items-start">
    <div class="d-flex w-100 justify-content-between">
      <h5 class="mb-1"><%= contact.full_name %> </h5>
      <small><%= link_to 'View', contact, class: "btn btn-outline-info btn-sm", role: "link" %> <%= link_to 'Edit', edit_contact_path(contact), class: "btn btn-outline-warning btn-sm", role: "link" %> <%= link_to 'Delete', contact, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-outline-danger btn-sm", role: "link" %></small>
    </div>
  </div>
  <% end %>
</div>
<div class="mt-5">
  <%= link_to 'New Contact', new_contact_path, class: "btn btn-primary" %>
</div>

app/views/contacts/new.html.erb
<div class="row">
	<div class="col-md-6 offset-md-3">
		<div class="card">
			<div class="card-header">
				<h1 class="card-title h3">New Contact</h1>
			</div>
			<div class="card-body">
				

				<%= render 'form', contact: @contact %>

				<%= link_to 'Back', contacts_path %>
			</div>
		</div>

	</div>
	
</div>

app/views/contacts/show.html.erb
<div class="row">
  <div class="col-md-6 offset-md-3">
    <div class="card">
     
      <div class="card-body">
        <div class="media">
          <%= image_tag @contact.my_avatar, class: "mr-3" %>
          
          <div class="media-body">
            <h5 class="mt-0"><%= @contact.full_name %></h5>
            <h6><%= @contact.company %></h6>
            <p class="font-weight-bold">Phones:</p>
            <ul>
            <% @contact.phones.each do |phone| %>
              <li><%= phone.phone_number %></li>
            <% end %>
            </ul>
            <p class="font-weight-bold">Email:</p>
            <ul>
            <% @contact.emails.each do |email| %>
              <li><%= email.my_email %></li>
            <% end %>
            </ul>
            <p class="font-weight-bold">Address:</p>
            <ul>
            <% @contact.addresses.each do |address| %>
              <li><%= address.my_address %></li>
            <% end %>
            </ul>
          </div>
        </div>
      <%= link_to 'Edit', edit_contact_path(@contact) %> |
      <%= link_to 'Back', contacts_path %>
      </div>
   
      
    </div>
  </div>
</div>

app/views/layouts/_flash.html.erb
<div class="alert alert-success alert-dismissible fade show" role="alert">
 <%= notice %>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Phonebook</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <section class="container-fluid mt-3">
      <%= yield %>
    </section>
  </body>
</html>